#!/bin/sh

set -e

case "$1" in
	remove|upgrade|deconfigure)
		# systemd: On uninstall (not upgrade), disable and stop the unit
		which systemctl >/dev/null 2>&1 && {
			systemctl --no-reload disable all-knowing-dns.service >/dev/null 2>&1 || true
			systemctl stop all-knowing-dns.service >/dev/null 2>&1 || true
		} || true
		;;
	
	failed-upgrade)
		;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
