#!/bin/sh

set -e

case "$1" in
	configure)
		# systemd: enable the service file so that it will be started
		# when booting. The server will be started later in this script
		# via the sysvinit compatibility layer.
		which systemctl >/dev/null 2>&1 && {
			systemctl enable all-knowing-dns.service >/dev/null 2>&1 || true
		} || true
		;;
	
	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
