#!/bin/sh

set -e

# systemd: reload the daemon
which systemctl >/dev/null 2>&1 && {
	systemctl daemon-reload >/dev/null 2>&1 || true
} || true

case "$1" in
	upgrade)
		# systemd: start the new version of all-knowing-dns
		which systemctl >/dev/null 2>&1 && {
			systemctl restart all-knowing-dns.service
		} || true
		;;
	
	purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
